spring:
  datasource:
    url: jdbc:mysql://localhost:8889/pool2?useSSL=false
    username: root
    password: root
    validation-query: SELECT 1
    test-on-borrow: true
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update 
      dialect: org.hibernate.dialect.MySQL5
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: false
  application:
    name: order-service
  data:
    rest:
      base-path: /api


server:
  port: 8084

  
#liquibase:
#  change-log: classpath:liquibase/db.changelob.xml